development: &default
  adapter: postgresql
  encoding: unicode
  database: afr_load_rails_development
  pool: 5
  username: postgres
  password:
  host: db
  port: 5432

test:
  <<: *default
  database: afr_load_rails_test

production:
  adapter:  postgresql
  pool: 5
  timeout: 5000
  database: production #db/production.sqlite3
