# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e75d7cfe0f9f4e338160c66a04a772eab95dedbf28065a7b47b331e0ceb9814e3f4524cd69e24b1235ecf172d9523383865b3ff595be0afe7e6c8a8a8e35960c

test:
  secret_key_base: 718468ec3ac8d1c60c1cc81857a9d920493333c6bf139b365029d7a10bbc7539660dffc23d52307fa99ed0cadb090d30c16024bd5392ee51eccf95bdcf52c3b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
